---
overrides:
  # Always wrap markdown
  - files: "*.md"
    options:
      proseWrap: always
  # Preserve wrap for yaml as wrapping make some commands less readable
  - files: "*.{yaml,yml}"
    excludeFiles: "content/**/*.{yaml,yml}"
    options:
      proseWrap: preserve
  # But hard wrap plaintext databases
  - files: "content/**/*.{yaml,yml}"
    options:
      proseWrap: always
